// 1 = hail
// 2 = junoub
// 3 = hasa
// 4 = hejaz
// 5 = qas
// 6 = naj

export const questions = [
    {
      key: 1,
      question: "ییزي",
      label: "يكفي",
      answers: [
        {
          "label": "يكفي",
          "region1value": "10",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "9",
        },
        {
          "label": "يشرب",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "نوع من أنواع الأحذية وأنتم بكرامة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 2,
      question: "جغمة",
      label: "رشفة",
      answers: [
        {
          "label": "حفرة عميقة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "رشفة",
          "region1value": "10",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "9",
          "region6value": "5",
        },
        {
          "label": "ثقيلة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 3,
      question: "هاليودعه",
      label: "من أجل ذلك",
      answers: [
        {
          "label": "من أجل ذلك",
          "region1value": "10",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "لننتظر قليلًا",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "دعنا لنودعه",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 4,
      question: "یتمقل",
      label: "يمعن النظر",
      answers: [
        {
          "label": "يعبس في وجهك",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "يغش ",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "يمعن النظر",
          "region1value": "10",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "9",
          "region6value": "5",
        }]
    },
    {
      key: 5,
      question: "شفايه",
      label: "فضول",
      answers: [
        {
          "label": "فضول",
          "region1value": "10",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "2",
        },
        {
          "label": "سفره",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "منظر جميل",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 6,
      question: "جماھو",
      label:  "أليس كذلك",
      answers: [
        {
          "label": "رفض شديد اللهجة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "مضحك ",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "أليس كذلك",
          "region1value": "10",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 7,
      question: "فرقزت",
      label: "قمت مذعورا",
      answers: [
        {
          "label": "قمت مذعورا",
          "region1value": "0",
          "region2value": "10",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ركضت سريعًا",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "تجهزت للعمل",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 8,
      question: "مید من",
      label: "من تقصد؟",
      answers: [
        {
          "label": "أين تذهب؟",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "أين صنع؟",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "من تقصد؟",
          "region1value": "0",
          "region2value": "10",
          "region3value": "4",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 9,
      question: "منقعر",
      "label": "منسدح على ظهره",
      answers: [
        {
          "label": "منسدح على ظهره",
          "region1value": "1",
          "region2value": "10",
          "region3value": "0",
          "region4value": "3",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "مائل أو غير مستوي",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "مسطح الشكل",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 10,
      question: "ارقه",
      "label": "هذا هو",
      answers: [
        {
          "label": "صحيح بلا شك",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "هذا هو",
          "region1value": "3",
          "region2value": "10",
          "region3value": "2",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "يكفي هذا القدر",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 11,
      question: "ھب لي",
      "label": "أعطني",
      answers: [
        {
          "label": "أعطني",
          "region1value": "0",
          "region2value": "10",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "خذ مني",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "اذهب عني",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 12,
      question: "حندرفیني",
      "label": "نظر إلي بغضب",
      answers: [
        {
          "label": "اسم جني في عسير",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "نظر إلي بغضب",
          "region1value": "0",
          "region2value": "10",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ضربني في كتفي",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 13,
      question: "خاشوقة",
      "label": "ملعقة",
      answers: [
        {
          "label": "ثلاجة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "إبرة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ملعقة",
          "region1value": "0",
          "region2value": "3",
          "region3value": "10",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 14,
      question: "عرموط",
      "label": "كمثرى",
      answers: [
        {
          "label": "كمثرى",
          "region1value": "1",
          "region2value": "0",
          "region3value": "10",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "برتقال",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "بطيخ",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 15,
      question: "باصج",
      "label": "قليل الملح",
      answers: [
        {
          "label": "عنيد",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "قليل الملح",
          "region1value": "3",
          "region2value": "1",
          "region3value": "10",
          "region4value": "0",
          "region5value": "2",
          "region6value": "0",
        },
        {
          "label": "جميل الرائحة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 16,
      question: "صمندیقة",
      "label": "الشخص الغبي",
      answers: [
        {
          "label": "الشخص الغني",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "الشخص المتباهي",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "الشخص الغبي",
          "region1value": "0",
          "region2value": "0",
          "region3value": "10",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 17,
      question: "غرشة",
      "label": "علبة",
      answers: [
        {
          "label": "علبة",
          "region1value": "0",
          "region2value": "2",
          "region3value": "10",
          "region4value": "1",
          "region5value": "3",
          "region6value": "0",
        },
        {
          "label": "مغرفة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "سكينة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 18,
      question: "غلج",
      "label": "صعب",
      answers: [
        {
          "label": "قاسي",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ثقيل",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "صعب",
          "region1value": "2",
          "region2value": "1",
          "region3value": "10",
          "region4value": "2",
          "region5value": "1",
          "region6value": "0",
        }]
    },
    {
      key: 19,
      question: "یمصع",
      "label": "يجر",
      answers: [
        {
          "label": "يطلب",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "يجر",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "10",
          "region5value": "10",
          "region6value": "8",
        },
        {
          "label": "يهرب",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 20,
      question: "مخمج",
      "label": "متعفن",
      answers: [
        {
          "label": "متعفن",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "10",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "معلب",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "وسخ",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 21,
      question: "بكرج",
      "label": "برادة",
      answers: [
        {
          "label": "صحن",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "كأس",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "برادة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "10",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 22,
      question: "یتمردغ",
      "label": "يتبهذل",
      answers: [
        {
          "label": "يلعب",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "يتبهذل",
          "region1value": "4",
          "region2value": "2",
          "region3value": "3",
          "region4value": "10",
          "region5value": "10",
          "region6value": "7",
        },
        {
          "label": "يحمل",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 23,
      question: "ستیتة",
      "label": "الأخت الكبرى",
      answers: [
        {
          "label": "الأخت الكبرى",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "10",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "أم الزوجة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "الجدة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 24,
      question: "الدقیسي",
      "label": "غرفة تحت الدرج",
      answers: [
        {
          "label": "دورة المياه",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "مجلس الضيوف",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "غرفة تحت الدرج",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "10",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 25,
      question: "تھقى",
      "label": "تظن",
      answers: [
        {
          "label": "تظن",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "8",
        },
        {
          "label": "تحتسي القهوى",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ترمي",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 26,
      question: "فاردز",
      "label": "ارحل",
      answers: [
        {
          "label": "شارك",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ارحل",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "7",
        },
        {
          "label": "اقترب",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 27,
      question: "مصع",
      "label": "يشد بقوة",
      answers: [
        {
          "label": "بالغ بالأمر",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "يشد بقوة",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "6",
        },
        {
          "label": "هدد بالموضوع",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 28,
      question: "ھماه",
      "label": "أليس كذلك؟",
      answers: [
        {
          "label": "أليس كذلك؟",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "3",
        },
        {
          "label": "جلب لي الهم والنكد",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ملك له",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 29,
      question: "احترين",
      "label": "انتظريني",
      answers: [
        {
          "label": "انتظريني",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "3",
        },
        {
          "label": "شارع في حي الخبوب",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "يكاد يحترق من الحرارة ",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 30,
      question: "أزمل",
      "label": "أخشى عواقب أمر ما",
      answers: [
        {
          "label": "أخشى عواقب أمر ما",
          "region1value": "2",
          "region2value": "1",
          "region3value": "3",
          "region4value": "0",
          "region5value": "10",
          "region6value": "8",
        },
        {
          "label": "أستعد للقدوم",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "أكثر جمالًا",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 31,
      question: "زاھب",
      "label": "جاهز",
      answers: [
        {
          "label": "راكب",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "جالس",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "جاهز",
          "region1value": "6",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "10",
        }]
    },
    {
      key: 32,
      question: "صایل",
      "label": "غاضب",
      answers: [
        {
          "label": "ولهان لشدة الشوق",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "غاضب",
          "region1value": "2",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "9",
          "region6value": "10",
        },
        {
          "label": "يدمع من الفرح",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 33,
      question: "عذروب",
      "label": "عيب",
      answers: [
        {
          "label": "عيب",
          "region1value": "6",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "10",
        },
        {
          "label": "من أسماء الخيل",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "عذر",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }]
    },
    {
      key: 34,
      question: "ھجت به",
      "label": "ضاعت علومه",
      answers: [
        {
          "label": "كتبت فيه أبياتًا من الشعر",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ساعدته",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ضاعت علومه",
          "region1value": "3",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "10",
        }]
    },
    {
      key: 35,
      question: "ذروق",
      "label": "جبان",
      answers: [
        {
          "label": "كريم",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "بخيل",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "جبان",
          "region1value": "4",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "10",
        }]
    },
    {
      key: 36,
      question: "احلت",
      "label": "ارم",
      answers: [
        {
          "label": "انهض",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        },
        {
          "label": "ارم",
          "region1value": "5",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "10",
          "region6value": "10",
        },
        {
          "label": "خذ",
          "region1value": "0",
          "region2value": "0",
          "region3value": "0",
          "region4value": "0",
          "region5value": "0",
          "region6value": "0",
        }
      ]
    }
  ];